---
exclude_patterns:
  - "node_modules/"
  - "languages/"
  - "vendor/"
  - "js/vendor/"
  - ".sass-cache/"
  - "*.min.js"
  - "css/"
  - "**/*.css"
  - "js/script.js"
  - "**/*.map"
  - "images/"
  - ".github/"

prepare:
  fetch:
    - url: "https://raw.githubusercontent.com/bu-ist/coding-standards/master/code-climate-rule-sets/.stylelintrc.json"
      path: ".stylelintrc.json"
    - "https://raw.githubusercontent.com/bu-ist/coding-standards/master/code-climate-rule-sets/.eslintrc"
    - "https://raw.githubusercontent.com/bu-ist/coding-standards/master/code-climate-rule-sets/.eslintignore"
    - "https://raw.githubusercontent.com/bu-ist/coding-standards/master/code-climate-rule-sets/.mdlrc"
    - "https://raw.githubusercontent.com/bu-ist/coding-standards/master/code-climate-rule-sets/markdown.rb"

engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - php
    exclude_paths:
      - "Gruntfile.js"
  eslint:
    enabled: false
    channel: eslint-5
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: php
      standard: WordPress
      ignore_warnings: false
      encoding: utf-8
  phpmd:
    enabled: true
    config:
      file_extensions: php
      rulesets: codesize,naming,unusedcode
  stylelint:
    enabled: true
    config:
      file_extensions: scss
ratings:
  paths:
    - "**.md"
    - "**.inc"
    - "**.js"
    - "**.json"
    - "**.php"
    - "**.scss"
