files:
  include: '**/*.s+(a|c)ss'
  ignore:
rules:
  # Not allowed at all
  border:
    - 2
    - convention: 'none'
  brace-style:
    - 2
    - allow-single-line: false
  clean-import-paths: 2
  empty-args: 2
  empty-line-between-blocks:
    - 2
    - allow-single-line-rulesets: false
  extends-before-declarations: 2
  extends-before-mixins: 2
  force-element-nesting: 2
  force-pseudo-nesting: 2
  hex-length: 2
  hex-notation: 2
  leading-zero:
    - 2
    - true
  mixins-before-declarations: 2
  no-empty-rulesets: 2
  no-color-keywords: 2
  placeholder-in-extend: 2
  one-declaration-per-line: 2
  single-line-per-selector: 2
  nesting-depth: 2
  no-invalid-hex: 2
  no-misspelled-properties: 2
  no-qualifying-elements:
    - 2
    - allow-element-with-attribute: true
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 2
  no-url-protocols: 2
  quotes:
    - 2
    - style: double
  shorthand-values: 2
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-bang: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 2
  trailing-semicolon: 2
  url-quotes: 2
  zero-unit: 2
  class-name-format:
    - 2
    -
      convention: (?!^col-)^[a-z][a-zA-Z0-9-?]*$
      convention-explanation: 'Classes may not use UPPERCASE or underscores. Additonally, overriding the col- classes is prohibited.'
      allow-leading-underscore: false
  placeholder-name-format:
    - 2
    -
      convention:  (?!^col-)^[a-z][a-zA-Z0-9-?]*$
      convention-explanation: 'Please use camelCase and hyphenation for your placeholder naming.'
      allow-leading-underscore: false
  variable-name-format:
    - 0
    -
      convention:  (^[a-z][a-zA\--Z0-9]*$)
      convention-explanation: 'Please use camelCase and hyphenation for your variable naming.'
      allow-leading-underscore: false
  id-name-format:
    - 0
    -
      convention:  (^[a-z][a-zA\--Z0-9]*$)
      convention-explanation: 'Please use camelCase and hyphenation for your ID naming.'
      allow-leading-underscore: false

  # Just a warning
  no-duplicate-properties:
    - 1
    - exclude:
      - display
  no-important: 1
  no-mergeable-selectors: 1
  no-vendor-prefixes: 1
  no-color-literals: 1
  # name-format: 0
  # property-sort-order: 1
  # property-spelling: 0
  # shorthand: 0

  # Stuff we don't care about
  no-css-comments: 0
  final-newline: 0
  no-ids: 0
  indentation: 0