version: "3.7"

services:
  wp-db:
    image: mariadb
    ports:
      - "8081:3306"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: ChangeMeIfYouWant
    volumes:
      - ./wp-db:/docker-entrypoint-initdb.d

  wordpress.local:
    build: .
    ports:
      - "80:80"
    links:
      - wp-db:mysql
    environment:
      WORDPRESS_DB_PASSWORD: ChangeMeIfYouWant
    volumes:
      - .:/var/www/html/wp-content/themes/responsive-framework-2-x

  backstopjs:
    image: backstopjs/backstopjs
    volumes:
      - .:/src
    command: ["--version"]
