version: "3.7"

services:
  wp-db:
    image: mariadb
    ports:
      - "8081:3306"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: ChangeMeIfYouWant
    volumes:
      - ./wp-db:/docker-entrypoint-initdb.d

  wordpress-backend:
    build: .
    links:
      - wp-db:mysql
    environment:
      WORDPRESS_DB_PASSWORD: ChangeMeIfYouWant
    volumes:
      - .:/var/www/html/wp-content/themes/responsive-framework-2-x
      - ./wp-media:/var/www/html/wp-content/uploads

  wordpress.local:
    image: bostonuniversity/elb-simulator:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      REMOTE_URL: "http://wordpress-backend"
      CERT_CN: wordpress.local
    depends_on:
      - "wordpress-backend"
    volumes:
      - ./ssl:/ssl

  backstopjs:
    image: backstopjs/backstopjs
    volumes:
      - .:/src
    command: ["--version"]
