version: "3.7"

services:
  wp-db:
    image: mariadb
    ports:
      - "8081:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMeIfYouWant

  wp:
    build: .
    ports:
      - "8080:80"
    links:
      - wp-db:mysql
    environment:
      WORDPRESS_DB_PASSWORD: ChangeMeIfYouWant
    volumes:
      - .:/var/www/html/wp-content/themes/responsive-framework-2-x
